version: '3'

services:

  dev_maja_db:
    container_name: dev_maja_db
    image: postgres:14.4-alpine
    restart: unless-stopped
    env_file: "$PWD/.env"
    environment:
      POSTGRES_DB: ${DATABASE_DEFAULT_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    expose:
      - "${DATABASE_PORT}"
    volumes:
      - "$PWD/scripts/database/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"
      - dev_maja_db_data:/var/lib/postgresql/data
    command: ["postgres"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      hoitekBridge:

  dev_maja_mongodb:
    image: mongo:4.4
    restart: unless-stopped
    container_name: dev_maja_mongodb
    env_file: "$PWD/.env"
    expose:
      - "${DATABASE_MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 111111
      MONGO_INITDB_DATABASE: majadb
    volumes:
      - dev_maja_mongodb_data:/data/db
    networks:
      hoitekBridge:

  dev_maja_rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: dev_maja_rabbitmq
    expose:
      - "${RABBITMQ_PORT}"
    ports:
      - "${RABBITMQ_PANEL_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    restart: unless-stopped
    networks:
      hoitekBridge:

  dev_maja_service:
    environment:
      # go private
      - GOPRIVATE=gitlab.hoitek.fi,github.com/hoitek/*
    container_name: dev_maja_service
    build:
      context: .
      dockerfile: Dockerfile.local
    working_dir: /app
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/healthcheck" ]
      interval: 10s
      timeout: 10s
      retries: 3
    expose:
      - "9090"
    ports:
      - "9090:9090"
    command:
      - 'dockerize'
      - '-wait'
      - 'tcp://dev_maja_db:5432'
      - '-timeout'
      - '10s'
      - './scripts/dev.sh'
    volumes:
      # - $HOME/.ssh:/root/.ssh
      - $PWD/.gitconfig:/root/.gitconfig
      - $PWD/:/app
    depends_on:
      dev_maja_db:
        condition: service_healthy
      dev_maja_rabbitmq:
        condition: service_started
    networks:
      hoitekBridge:
    restart: unless-stopped

volumes:
  dev_maja_db_data:
  dev_maja_mongodb_data:
  rabbitmq_data:
  rabbitmq_logs:

networks:
  hoitekBridge:
    external: true