package constants

const (
	CUSTOMER_MEDICINE_DOSAGE_UNIT_GRAM       = "gram"
	CUSTOMER_MEDICINE_DOSAGE_UNIT_MILLIGRAM  = "milligram"
	CUSTOMER_MEDICINE_DOSAGE_UNIT_MICROGRAM  = "microgram"
	CUSTOMER_MEDICINE_DOSAGE_UNIT_LITER      = "liter"
	CUSTOMER_MEDICINE_DOSAGE_UNIT_MILLILITER = "milliliter"
	CUSTOMER_MEDICINE_DOSAGE_UNIT_TEASPOON   = "teaspoon"
)
